### ISSUE TITLE
Theme Change of ToolBar

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/pyqt-light-gray-theme#2]
Hi, there. There might be a little problem of ToolBar cause when switching between differet themes, the border color of ToolBar doesn't change, remaining the default like this:
![image](https://user-images.githubusercontent.com/97718634/214091475-ed29088e-e773-440b-a0c9-705fb206992c.png)
Anyway, it's no big deal. If you think it's a bother, please leave it alone.
Looking forward to your reply^^

**Comment by yjg30737** [comment]
Is it QMdiSubWindow?

It looks more like it rather than QToolBar

**Comment by Liskelleo** [comment]
Oops, maybe I’m wrong. It’s Dockwidget.

**Comment by yjg30737** [comment]
OK, Now it should work. There was no style for QDockWidget in the first place, so i've added the style and appropriate icon.

That indeed change the style of the title bar of qdockwidget, but it is only for docked one. It doesn't change the undocked qdockwidget's title bar, according to the <a href="https://doc.qt.io/qt-6/stylesheet-reference.html">docs</a>. They say

```
The style sheet has no effect when the [QDockWidget](https://doc.qt.io/qt-6/qdockwidget.html) is undocked 
as Qt uses native top level windows when undocked.
```

So if you want to do it you need to declare the custom title bar and set that with <a href="https://doc.qt.io/qt-6/qdockwidget.html#setTitleBarWidget">setTitleBarWidget</a>.

**Comment by Liskelleo** [comment]
Ok, it works well for me. Thank you^^
